Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -86,6 +86,19 @@ jobs:
         os_patch_level: ${{ inputs.os_patch_level }}
         use_repo: ${{ inputs.use_repo }}
 
+    - name: Apply HideNew Patch
+      shell: bash
+      working-directory: ${{ github.workspace }}/kernel/common
+      run: |
+        set -euo pipefail
+        PATCH="${{ github.workspace }}/kernel_patches/hidenew.patch"
+        if patch -p1 --dry-run < "$PATCH"; then
+          patch -p1 --no-backup-if-mismatch < "$PATCH"
+        else
+          echo "Failed to apply hidenew.patch"
+          exit 1
+        fi
+
     - name: Set Build Timestamp from Kernel Commit
       shell: bash
       run: |
@@ -182,19 +195,6 @@ jobs:
       with:
         version: ${{ inputs.version }}
         kernel_version: ${{ inputs.kernel_version }}
-
-    - name: Apply HideNew Patch
-      shell: bash
-      working-directory: ${{ github.workspace }}/kernel/common
-      run: |
-        set -euo pipefail
-        PATCH="${{ github.workspace }}/kernel_patches/hidenew.patch"
-        if patch -p1 --dry-run < "$PATCH"; then
-          patch -p1 --no-backup-if-mismatch < "$PATCH"
-        else
-          echo "Failed to apply hidenew.patch"
-          exit 1
-        fi
 
     - name: Apply ABI Compare Bypass
       if: false
